### PR TITLE
Vendors signup handler

### PR DESCRIPTION
**Pull request by chibuike07**

### CODE REVIEW

**Review by jobizil — COMMENTED** [review]
Instead of using res.send, I'll advise you to use res.json because res.send has been deprecated.

**Comment by chibuike07** [comment]
> Instead of using res.send, I'll advise you to use res.json because res.send has been deprecated.

Alright noted, thanks for the check, it will be corrected. If there is no other changes you may wish to correct, you approve the request. Weldon

**Review by jobizil — DISMISSED** [review]
Nice work bro, you still have the res.send though.

**Comment by chibuike07** [comment]
> Nice work bro, you still have the res.send though.

I have, oncct again thanks for notice

**Review by jobizil — DISMISSED** [review]

**Review by HENRYKC24 — APPROVED** [review]

**Review by jobizil — APPROVED** [review]

**Pull request merged**
